[communications]
    port = 4201

[core]
    port = 4200

[taskmanager]
    port = 4202

[postgresql]
    host = "localhost"
    database_name = "nexus"
    username = "nexus"
    password = "nexus"

[inference]
    port = 4203